---

driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
  - name: centos/6
  - name: centos/7
  - name: debian/wheezy64
  - name: debian/jessie64

suites:
  - name: default
    run_list:
      - recipe[cop_magento::users]
      - recipe[cop_magento::cli-tools]
      - recipe[cop_magento::permissions]
      - recipe[cop_magento::robots]
      - recipe[cop_magento::composer-prep]
    attributes:
      robots:
        allow: false
      magento:
        directories:
          test_dir:
            path:  '/var/test'
            owner: 'root'
            group: 'root'
            mode:  0755
          composer_home:
            path:  '/tmp/.composer'
            owner: 'root'
            group: 'root'
            mode:  0755
          magento_composer_home:
            path:  '/tmp/composer_home'
            owner: 'root'
            group: 'root'
            mode:  0755
          magento:
            path:  '/tmp/magento'
            owner: 'root'
            group: 'root'
            mode:  0755
        files:
          test_file:
            path:  '/var/test.file'
            owner: 'root'
            group: 'root'
            mode:  0755
