---

driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  environments_path: "test/integration/environments"
  client_rb:
    environment: development

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
  - name: centos/6
  - name: centos/7
  - name: debian/wheezy64
  - name: debian/jessie64

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/data_bag_encrypted_secret_key"
    run_list:
      - recipe[cop_base]
      - recipe[cop_magento::users]
      - recipe[cop_php]
      - recipe[cop_nginx]
      - recipe[cop_magento::data-bag]
      - recipe[cop_mysql::install_client]
      - recipe[cop_mysql::install_server]
      - recipe[cop_redis]
      - recipe[cop_composer::install]
      - recipe[cop_magento]
    attributes:
      robots:
        allow: false
      magento:
        directories:
          test_dir:
            path:  '/var/test'
            owner: 'root'
            group: 'root'
            mode:  0755
        files:
          test_file:
            path:  '/var/test.file'
            owner: 'root'
            group: 'root'
            mode:  0755
