---

driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero
  require_chef_omnibus: 13.1.31
  # Last tested version
  environments_path: "test/integration/environments"
  client_rb:
    environment: development

platforms:
  - name: ubuntu/trusty64
  - name: ubuntu/xenial64
  - name: centos/7
  - name: centos/6

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    encrypted_data_bag_secret_key_path: "test/integration/data_bag_encrypted_secret_key"
    run_list:
      - recipe[cop_base]
      - recipe[cop_cron]
      - recipe[cop_users]
      - recipe[cop_nginx]
      - recipe[cop_php]
      - recipe[cop_magento::data-bag]
      - recipe[cop_mysql::install_client]
      - recipe[cop_mysql::install_server]
      - recipe[cop_redis]
      - recipe[cop_varnish]
      - recipe[cop_composer::install]
      - recipe[cop_magento::full-install]
    attributes:
      robots:
        allow: true
        user_agents:
          test-agent:
            - 'path/to/file'
            - 'var/www/*'
        sitemaps:
          example.com: 'http://www.example.com/sitemap.xml'
      magento:
        additional_domains:
          - "example.net"
